=== Borislav-K/XML-Project/resources/market.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT market (productType*,vendor*,products?)>
        <!ELEMENT productType (name)>
        <!ELEMENT vendor (name,city))>
        <!ELEMENT products (product*)>
        <!ELEMENT product (price)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST productType productTypeId ID #REQUIRED>
        <!ATTLIST vendor vendorId ID #REQUIRED>
        <!ATTLIST product
                upi ID #REQUIRED
                productTypeId IDREF #REQUIRED
                vendorId IDREF #REQUIRED>

=== Borislav-K/XML-Project/resources/example_shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE market SYSTEM "resources\market.dtd">
<market>
    <!--        PRODUCT TYPES        -->
    <productType productTypeId="p1">
        <name>Apple</name>
    </productType>
    <productType productTypeId="p2">
        <name>Jacket</name>
    </productType>

    <!--           VENDORS           -->
    <vendor vendorId="v1">
        <name>vendor1</name>
        <city>Sofia</city>
    </vendor>
    <vendor vendorId="v2">
        <name>vendor2</name>
        <city>Plovdiv</city>
    </vendor>

    <!--          PRODUCTS           -->
    <products>
        <product upi="upi1" productTypeId="p1" vendorId="v1">
            <price>0.95BGN</price>
        </product>

        <product upi="upi2" productTypeId="p1" vendorId="v2">
            <price>0.60$</price>
        </product>

        <product upi="upi3" productTypeId="p2" vendorId="v2">
            <price>35.00$</price>
        </product>
    </products>
</market>
